version: '3.8'

services:
  # caddy:
  # ngrok:
  # sc-deployer:
  # sc-deployment-server:
  geth:
    image: ethereum/client-go:v1.15.0
    container_name: geth
    entrypoint: ['/entrypoint.sh']
    volumes:
      - ./geth/entrypoint.sh:/entrypoint.sh:ro
      - ./geth_data:/root/.ethereum
    ports:
      - '8545:8545'
      - '8546:8546'

  geth-init:
    image: ethereum/client-go:v1.15.0
    container_name: geth-init
    entrypoint: ['/entrypoint.sh']
    volumes:
      - ./geth-init/entrypoint.sh:/entrypoint.sh:ro
      - ./geth-init/prefund.js:/scripts/prefund.js:ro
    depends_on:
      - geth
    network_mode: 'service:geth'
  # graph-ipfs:
  # graph-postgres:
  # graph-redis:
  # graph-node:

  # blockscout: should be another docker-compose.yml file from https://github.com/blockscout/blockscout/tree/master/docker-compose. Don't create a container in this file.
